In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re

In [2]:
data=pd.read_csv(r"C:\Users\AAYUSH JHA\Downloads\WELFake_Dataset.csv")
data

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1
...,...,...,...,...
72129,72129,Russians steal research on Trump in hack of U....,WASHINGTON (Reuters) - Hackers believed to be ...,0
72130,72130,WATCH: Giuliani Demands That Democrats Apolog...,"You know, because in fantasyland Republicans n...",1
72131,72131,Migrants Refuse To Leave Train At Refugee Camp...,Migrants Refuse To Leave Train At Refugee Camp...,0
72132,72132,Trump tussle gives unpopular Mexican leader mu...,MEXICO CITY (Reuters) - Donald Trump’s combati...,0
72133,72133,Goldman Sachs Endorses Hillary Clinton For Pre...,Goldman Sachs Endorses Hillary Clinton For Pre...,1

In [3]:
data.dropna(inplace=True)

In [4]:
data=data.drop(['Unnamed: 0'],axis=1)

In [5]:
data['title']=data['title'].apply(lambda x:x.lower())
data

,title,text,label
0,law enforcement on high alert following threat...,No comment is expected from Barack Obama Membe...,1
2,unbelievable! obama’s attorney general says mo...,"Now, most of the demonstrators gathered last ...",1
3,"bobby jindal, raised hindu, uses story of chri...",A dozen politically active pastors came here f...,0
4,satan 2: russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1
5,about time! christian group sues amazon and sp...,All we can say on this one is it s about time ...,1
...,...,...,...
72129,russians steal research on trump in hack of u....,WASHINGTON (Reuters) - Hackers believed to be ...,0
72130,watch: giuliani demands that democrats apolog...,"You know, because in fantasyland Republicans n...",1
72131,migrants refuse to leave train at refugee camp...,Migrants Refuse To Leave Train At Refugee Camp...,0
72132,trump tussle gives unpopular mexican leader mu...,MEXICO CITY (Reuters) - Donald Trump’s combati...,0
72133,goldman sachs endorses hillary clinton for pre...,Goldman Sachs Endorses Hillary Clinton For Pre...,1

In [6]:
print(data.columns.tolist())

['title', 'text', 'label']

In [7]:
X=data['title']
Y=data['label']
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer(stop_words='english',max_df=0.7)

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=42)

In [9]:
X_train_vec=vectorizer.fit_transform(X_train)
X_test_vec=vectorizer.transform(X_test)

In [10]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=60,random_state=42)
rf.fit(X_train_vec,Y_train)

RandomForestClassifier(n_estimators=60, random_state=42)

In [11]:
Y_pred=rf.predict(X_test_vec)

In [12]:
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(Y_test,Y_pred)
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.91      0.89      0.90     10595
           1       0.90      0.91      0.91     10867

    accuracy                           0.90     21462
   macro avg       0.90      0.90      0.90     21462
weighted avg       0.90      0.90      0.90     21462

In [13]:
rf.score(X_test_vec,Y_test)

0.903270897400056

In [24]:
news ="""law enforcement on high alert following threats against cops and whites on 9-11by #blacklivesmatter and #fyf911 terrorists [video]"""

if news.lower() in data['title'].values:
    print("hello")
else:
    print("not")

hello

In [15]:
rf.predict_proba(text_vect)

NameError: name 'text_vect' is not defined

In [ ]:
import pickle
pickle.dump(rf,open('model.pkl','wb'))
pickle.dump(vectorizer,open('vect.pkl','wb'))

In [ ]:
from joblib import dump
dump(rf,'compressmodel.joblib',compress=('zlib', 5))

In [ ]:
dump(vectorizer, 'vectorizer_compressed.joblib', compress=('zlib', 5))

In [23]:
data['title'][2]

'unbelievable! obama’s attorney general says most charlotte rioters were “peaceful” protesters…in her home state of north carolina [video]'

In [ ]:
rf.predict_proba(text_vect)[0][0]>rf.predict_proba(text_vect)[0][1]

In [ ]:
lse:
    
    import requests

    url = "https://newsdata.io/api/1/latest"
    params = {
        "apikey": "pub_c8b49d885fa74b248b80aefa03b11a70",
        "q": news,
        "language": "en",
    }

    response = requests.get(url, params=params)
    data=response.json()
    if data['status'] == 'success' and data['totalResults'] > 0:
        print("It's a real news")
    else:
        print("Fake news")